### ISSUE TITLE
The claim to have examined "all defenses accepted to ICLR 2018" is incorrrect

### ISSUE THREAD

**Issue by goodfeli** [anishathalye/obfuscated-gradients#1]
Your paper says that it excludes three accepted ICLR 2018 papers: two that have certifiable defenses, and one that concerns only the black box case. However, this github repository says that your case study examines "all defenses" without any qualifications. The abstract of your paper also says "all defenses" incorrectly. This should be qualified to "all non-certified defenses in the white box setting" in all cases.

**Comment by carlini** [comment]
Definitely true -- apologies. We will correct this.

**Comment by goodfeli** [comment]
Thanks, looking forward to the correction.

**Comment by anishathalye** [comment]
This has been resolved in the latest paper draft.

**Comment by goodfeli** [comment]
Thanks!
