### ISSUE TITLE
Code is nowhere to be found in this repo

### ISSUE THREAD

**Issue by fac2003** [anishathalye/obfuscated-gradients#3]
The README claims that code is included in the repo, but there is none. I am surprised others comment on the claims of the paper when the code that would support the claims is not open.

**Comment by anishathalye** [comment]
Thank you for your note. We hope you also saw that in the [next paragraph](https://github.com/anishathalye/obfuscated-gradients#source-code), we've said that we can share preview copies with researchers upon request. We'll have cleaned-up code online shortly.

Also, we'd like to note that once you have the idea, most of the attacks are actually quite straightforward to implement. [This blog post](http://www.anishathalye.com/2017/07/25/synthesizing-adversarial-examples/) (which incidentally was released a couple months before the ICLR submission deadline) walks through the process that's used to defeat input transformation-based defenses ([EOT](https://arxiv.org/abs/1707.07397))), if you're interested in that.
