### ISSUE TITLE
Test Pixel Deflection

### ISSUE THREAD

**Issue by iamaaditya** [anishathalye/obfuscated-gradients#4]
Hi

I would appreciate if you could test [Pixel Deflection](https://github.com/iamaaditya/pixel-deflection)  (even if it is without the RCAM). Or if you could share the code with me I could test and report the numbers to you. My email is aprakash @ brandeis.edu

**Comment by carlini** [comment]
The code is now available, we would be happy to hear if you try this attack on Pixel Deflection (success or failure).
