### ISSUE TITLE
How do you keep distance to 0.031?

### ISSUE THREAD

**Issue by xuanqing94** [anishathalye/obfuscated-gradients#7]
Hi, I would like to test more defense algorithms, however I don't see the code that controls linf perturbation to 0.031 for all defense algorithms. I guess you were doing binary search on $c$ in CW attack?

**Comment by carlini** [comment]
If you look at the code you'll often see a
`self.epsilon = 8`
or
`EPSILON = 8.0`.

These are referring to 8/256 = 0.031.
